package de.linogistix.mobile.processes.fuel;

public enum FuelNavigationEnum {
	GRD_BACK_TO_MENU,
	GRD_ENTER_MAT,
	GRD_CHOOSE_GR,
	GRD_CHOOSE_POS,
	GRD_CONFIRM_AMOUNT,
	GRD_ENTER_UL_NO,
	GRD_ENTER_UL_TYPE,
	GRD_ENTER_AMOUNT,
	GRD_ENTER_LOT,
	GRD_ENTER_LOTDATE,
	GRD_ENTER_SERIAL,
	GRD_ENTER_TARGET_LOC,
	GRD_ENTER_TARGET_UL
}
