/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.logviewer.processes.log.gui.gui_builder;

import de.linogistix.common.gui.object.IconType;
import de.linogistix.common.util.GraphicUtil;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import org.mywms.globals.LogItemType;
import org.openide.util.Utilities;


/**
 *
 * @author  artur
 */
public abstract class AbstractCenterPanel extends javax.swing.JPanel {


    /** Creates new form AbstractCenterPanel */
    public AbstractCenterPanel() {
        initComponents();
        postCreationCode();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPanel = new javax.swing.JPanel();
        errorToggleButton = new javax.swing.JToggleButton();
        infoToggleButton = new javax.swing.JToggleButton();
        clearingToggleButton = new javax.swing.JToggleButton();

        setLayout(new java.awt.BorderLayout());

        buttonPanel.setLayout(new java.awt.GridBagLayout());

        errorToggleButton.setText("");
        errorToggleButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        errorToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                errorToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        buttonPanel.add(errorToggleButton, gridBagConstraints);

        infoToggleButton.setText("");
        infoToggleButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        infoToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        buttonPanel.add(infoToggleButton, gridBagConstraints);

        clearingToggleButton.setText("");
        clearingToggleButton.setMargin(new java.awt.Insets(2, 4, 2, 4));
        clearingToggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearingToggleButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        buttonPanel.add(clearingToggleButton, gridBagConstraints);

        add(buttonPanel, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void errorToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_errorToggleButtonActionPerformed
        errorToggleButtonActionPerformedListener(evt);
    }//GEN-LAST:event_errorToggleButtonActionPerformed

    private void infoToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoToggleButtonActionPerformed
        infoToggleButtonActionPerformedListener(evt);
    }//GEN-LAST:event_infoToggleButtonActionPerformed

    private void clearingToggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearingToggleButtonActionPerformed
        clearingToggleButtonActionPerformedListener(evt);
    }//GEN-LAST:event_clearingToggleButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JToggleButton clearingToggleButton;
    private javax.swing.JToggleButton errorToggleButton;
    private javax.swing.JToggleButton infoToggleButton;
    // End of variables declaration//GEN-END:variables
   
    private void postCreationCode() {
        ImageIcon iconImage = new ImageIcon(GraphicUtil.getInstance().iconToImage(GraphicUtil.getInstance().getIcon(IconType.ERROR)));
        errorToggleButton.setIcon(new ImageIcon(iconImage.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT)));        
        iconImage = new ImageIcon(GraphicUtil.getInstance().iconToImage(GraphicUtil.getInstance().getIcon(IconType.INFORMATION)));
        infoToggleButton.setIcon(new ImageIcon(iconImage.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT)));        
        iconImage = new ImageIcon(Utilities.loadImage("de/linogistix/common/res/icon/warning.png"));
        clearingToggleButton.setIcon(new ImageIcon(iconImage.getImage().getScaledInstance(16, 16, Image.SCALE_DEFAULT)));        
        clearingToggleButton.setSelected(true);
        errorToggleButton.setSelected(true);
    }

    /**
     * 
     * @return Which buttons are Selected
     */    
    public List<LogItemType> getButttonState() {
        List<LogItemType> l = new ArrayList<LogItemType>();
        if (infoToggleButton.isSelected()) {
           l.add(LogItemType.LOG);
        }
        if (errorToggleButton.isSelected()) {
           l.add(LogItemType.ERROR);
        }  
        return l;
    }
    
    public boolean isClearingButtonSelected() {        
        return clearingToggleButton.isSelected();
    }
    
    
    protected void infoToggleButtonActionPerformedListener(java.awt.event.ActionEvent evt) {
        
    }

    protected void errorToggleButtonActionPerformedListener(java.awt.event.ActionEvent evt) {
        
    }
    
    protected void clearingToggleButtonActionPerformedListener(java.awt.event.ActionEvent evt) {
        
    }
    
}
