/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.unitload.transfer.gui_builder;

import de.linogistix.wmsprocesses.stockunittransfer.gui.gui_builder.*;
import de.linogistix.common.gui.component.controls.BOAutoFilteringComboBox;
import de.linogistix.common.gui.component.controls.LosLabel;
import de.linogistix.los.location.model.LOSUnitLoad;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;
import org.mywms.model.StockUnit;
import org.openide.util.NbBundle;

/**
 *
 * @author  trautm
 */
public abstract class AbstractChooseSourcePanel extends javax.swing.JPanel {

    /** Creates new form AbstractCenterPanel */
    public AbstractChooseSourcePanel() {
        initComponents();
        getUnitLoadRemoveLockLabel().setTitleText(
                NbBundle.getMessage(WMSProcessesBundleResolver.class, "removeLock"));


        getUnitLoadRemoveReservationLabel().setTitleText(
                NbBundle.getMessage(WMSProcessesBundleResolver.class, "removeReservation"));


    }
       
    public LosLabel getUnitLoadRemoveReservationLabel(){
        return (LosLabel) ulReserveLabel;
    }
    
    public LosLabel getUnitLoadRemoveLockLabel(){
        return (LosLabel) ulLockLabel;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        unitLoadAutofilteringComboBox = new BOAutoFilteringComboBox(LOSUnitLoad.class);
        ulReserveCheckBox = new javax.swing.JCheckBox();
        ulLockCheckBox = new javax.swing.JCheckBox();
        ulLockLabel = new LosLabel();
        ulReserveLabel = new LosLabel();

        setAlignmentX(0.0F);
        setAlignmentY(0.0F);
        setAutoscrolls(true);
        setLayout(new java.awt.GridBagLayout());

        unitLoadAutofilteringComboBox.setAlignmentX(0.0F);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weighty = 0.5;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(unitLoadAutofilteringComboBox, gridBagConstraints);

        ulReserveCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulReserveCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        add(ulReserveCheckBox, gridBagConstraints);

        ulLockCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulLockCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 0, 0);
        add(ulLockCheckBox, gridBagConstraints);

        ulLockLabel.setText("sulockLabel");
        ulLockLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(ulLockLabel, gridBagConstraints);

        ulReserveLabel.setText("suReserveLabel");
        ulReserveLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(ulReserveLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

private void ulReserveCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulReserveCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ulReserveCheckBoxActionPerformed

private void ulLockCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulLockCheckBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_ulLockCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JCheckBox ulLockCheckBox;
    protected javax.swing.JLabel ulLockLabel;
    protected javax.swing.JCheckBox ulReserveCheckBox;
    protected javax.swing.JLabel ulReserveLabel;
    protected javax.swing.JPanel unitLoadAutofilteringComboBox;
    // End of variables declaration//GEN-END:variables

    
    public BOAutoFilteringComboBox getUnitLoadAutofilteringComboBox() {
        return (BOAutoFilteringComboBox) unitLoadAutofilteringComboBox;
    }
}
