/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.logviewer.processes.clearing.gui.gui_builder;

//import de.linogistix.common.gui.component.controls.multiLineTable.CalculateWarp;
import de.linogistix.common.gui.component.controls.table.radioButton.RadioButtonTable;
import de.linogistix.common.gui.component.controls.table.radioButton.RadioButtonTableModel;
import de.linogistix.common.gui.listener.MinimumSizeComponentListener;
import de.linogistix.common.res.CommonBundleResolver;
import de.linogistix.logviewer.res.BundleResolver;
import java.awt.Dialog;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.propertysheet.PropertySheet;
import org.openide.util.HelpCtx;
import org.openide.util.NbBundle;
import org.openide.util.Utilities;

/**
 *
 * @author  artur
 */
public class AbstractClearingDialog extends javax.swing.JPanel implements ExplorerManager.Provider, ActionListener {

    public DialogDescriptor dialogDescriptor;
    public Dialog dialog;
    public final static String OK_BUTTON = "OK";
    public final static String CANCEL_BUTTON = "CANCEL";
    protected PropertySheet detailView;
    private RadioButtonTableModel tableInput;
    private Object columnNames[] = {RadioButtonTableModel.OPTION_LABEL, RadioButtonTableModel.DESCRIPTION_LABEL};
    private Object tableData[][] = {};
    protected PropertySheet sheet = new PropertySheet();
    private final ExplorerManager mgr = new ExplorerManager();    
    
// Create options
    JButton options[] = new JButton[]{
        new CustomButton(NbBundle.getMessage(CommonBundleResolver.class, OK_BUTTON), OK_BUTTON),
        new CustomButton(NbBundle.getMessage(CommonBundleResolver.class, CANCEL_BUTTON), CANCEL_BUTTON)
    };

    /** Creates new form AbstractClearingDialog */
    public AbstractClearingDialog() {
        initComponents();
        postInit();
        dialogDescriptor = new DialogDescriptor(
                this,
                NbBundle.getMessage(BundleResolver.class, "Clearing"),
                true,
                options,
                options[1], //welcher defaultm�ssig selektiert sein soll
                DialogDescriptor.DEFAULT_ALIGN,
                null, //getHelpCtx(),
                this);
//        dialogDescriptor.setClosingOptions(close);  
        dialogDescriptor.setClosingOptions(new Object[]{options[1]});
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        northPanel = new javax.swing.JPanel();
        messageTextPane = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        center2Panel = new javax.swing.JPanel();
        splitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(600, 400));
        setPreferredSize(new java.awt.Dimension(600, 400));
        setLayout(new java.awt.BorderLayout());

        centerPanel.setPreferredSize(new java.awt.Dimension(500, 400));
        centerPanel.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        northPanel.setLayout(new java.awt.BorderLayout());

        messageTextPane.setBorder(null);
        messageTextPane.setEditable(false);
        messageTextPane.setFocusable(false);
        northPanel.add(messageTextPane, java.awt.BorderLayout.CENTER);

        jPanel2.add(northPanel, java.awt.BorderLayout.CENTER);

        jLabel1.setText("");
        jPanel1.add(jLabel1);

        jPanel2.add(jPanel1, java.awt.BorderLayout.WEST);

        centerPanel.add(jPanel2, java.awt.BorderLayout.NORTH);

        center2Panel.setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        splitPane.setLeftComponent(jScrollPane1);

        center2Panel.add(splitPane, java.awt.BorderLayout.CENTER);

        centerPanel.add(center2Panel, java.awt.BorderLayout.CENTER);

        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel center2Panel;
    protected javax.swing.JPanel centerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    protected javax.swing.JTextPane messageTextPane;
    private javax.swing.JPanel northPanel;
    protected javax.swing.JSplitPane splitPane;
    protected javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    public void createTable() {
        tableInput = new RadioButtonTableModel(tableData, columnNames);
        table = new RadioButtonTable(tableInput);
        jScrollPane1.getViewport().add(table);
        setSelectionListener();
        table.setShowVerticalLines(false);
        table.getTableHeader().setVisible(false);
        java.awt.Dimension d = new java.awt.Dimension(0, 0);
        table.getTableHeader().setPreferredSize(d);
        table.getColumnModel().setColumnMargin(0);
        table.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableInput.setRadioButtonRenderer(table, DefaultTableCellRenderer.LEFT, 25);
        messageTextPane.setBackground(northPanel.getBackground());       
    }

    private void createPropertySheet() {
        splitPane.setRightComponent(sheet);        
    }
    
    private void setSelectionListener() {
        table.getSelectionModel().addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                selectionChangedListener(e);
            }            
        });        
    }
    
    protected void selectionChangedListener(ListSelectionEvent e) {
        
    }
    
   
    public HelpCtx getHelpCtx() {
        return new HelpCtx("de.linogistix.ltu.processes.storage.res.help.help.html");
    }

    public void actionPerformed(final java.awt.event.ActionEvent ev) {
    }

    public void showDialog() {
        //The adding top Panel is responsible for the init size
        dialog = DialogDisplayer.getDefault().createDialog(dialogDescriptor);
        new MinimumSizeComponentListener(dialog);
        dialog.setModal(true);
        dialog.pack();
        dialog.setVisible(true);
    }

    public void closeDialog() {
        dialog.dispose();
    }

    protected void addRow(String text) {
        columnNames[0] = new JRadioButton("");
        columnNames[1] = text;
        tableInput.addRow(columnNames);
    }

    protected void setTitle(String text) {
        messageTextPane.setText(text);
    }

    private void postInit() {
        createTable();
        createPropertySheet();
        northPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));
        splitPane.setLeftComponent(jScrollPane1);
        splitPane.setOneTouchExpandable(true);
        ImageIcon iconImage = new ImageIcon(Utilities.loadImage("de/linogistix/common/res/icon/warning.png"));        
        jLabel1.setIcon(iconImage);
    }

    public class CustomButton extends JButton {

        public CustomButton(String title, String actionCommand) {
            super(title);
            setActionCommand(actionCommand);
        }
    }
    
    public ExplorerManager getExplorerManager() {
        
        return mgr;
    }
    
}




