/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.wmsprocesses.processes.goodsreceipt.gui.gui_builder;

import de.linogistix.common.gui.component.controls.LOSDateFormattedTextField;
import de.linogistix.common.gui.component.controls.LosLabel;
import de.linogistix.wmsprocesses.res.WMSProcessesBundleResolver;

/**
 *
 * @author  trautm
 */
public class AbstractCreateWizardDetailPanel extends javax.swing.JPanel {

    /** Creates new form AbstractCreateWizardDetailPanel */
    public AbstractCreateWizardDetailPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        goodsReceiptPanel = new javax.swing.JPanel();
        clientComboBoxPanel = new javax.swing.JPanel();
        gateComboBoxPanel = new javax.swing.JPanel();
        gateComboBox = new javax.swing.JComboBox();
        gateLabel = new LosLabel();
        delivererTextfield = new javax.swing.JTextField();
        delivererLabel = new javax.swing.JLabel();
        externNumberLabel = new javax.swing.JLabel();
        externNumberTextfield = new javax.swing.JTextField();
        datePanel = new LOSDateFormattedTextField();

        setLayout(new java.awt.BorderLayout());

        goodsReceiptPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Header"));
        goodsReceiptPanel.setLayout(new java.awt.GridBagLayout());

        clientComboBoxPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        goodsReceiptPanel.add(clientComboBoxPanel, gridBagConstraints);

        gateComboBoxPanel.setLayout(new java.awt.BorderLayout());

        gateComboBox.setMinimumSize(new java.awt.Dimension(150, 22));
        gateComboBox.setPreferredSize(new java.awt.Dimension(150, 22));
        gateComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gateComboBoxActionPerformed(evt);
            }
        });
        gateComboBoxPanel.add(gateComboBox, java.awt.BorderLayout.CENTER);

        gateLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "GoodsreceiptCenterPanel.gateLabel")); // NOI18N
        gateLabel.setMaximumSize(new java.awt.Dimension(300, 14));
        gateComboBoxPanel.add(gateLabel, java.awt.BorderLayout.NORTH);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        goodsReceiptPanel.add(gateComboBoxPanel, gridBagConstraints);

        delivererTextfield.setMinimumSize(new java.awt.Dimension(150, 22));
        delivererTextfield.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        goodsReceiptPanel.add(delivererTextfield, gridBagConstraints);

        delivererLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "GoodsreceiptCenterPanel.deliverer")); // NOI18N
        delivererLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        delivererLabel.setMaximumSize(new java.awt.Dimension(150, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        goodsReceiptPanel.add(delivererLabel, gridBagConstraints);

        externNumberLabel.setText(org.openide.util.NbBundle.getMessage(WMSProcessesBundleResolver.class, "AbstractCenterPanel.externNumberLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        goodsReceiptPanel.add(externNumberLabel, gridBagConstraints);

        externNumberTextfield.setMinimumSize(new java.awt.Dimension(150, 22));
        externNumberTextfield.setPreferredSize(new java.awt.Dimension(150, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        goodsReceiptPanel.add(externNumberTextfield, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        goodsReceiptPanel.add(datePanel, gridBagConstraints);

        add(goodsReceiptPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

private void gateComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gateComboBoxActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_gateComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JPanel clientComboBoxPanel;
    protected javax.swing.JPanel datePanel;
    private javax.swing.JLabel delivererLabel;
    protected javax.swing.JTextField delivererTextfield;
    private javax.swing.JLabel externNumberLabel;
    protected javax.swing.JTextField externNumberTextfield;
    protected javax.swing.JComboBox gateComboBox;
    private javax.swing.JPanel gateComboBoxPanel;
    protected javax.swing.JLabel gateLabel;
    private javax.swing.JPanel goodsReceiptPanel;
    // End of variables declaration//GEN-END:variables

}
