/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.logviewer.processes.log;

import de.linogistix.common.gui.listener.TopComponentListenerImpl;
import de.linogistix.common.gui.listener.TopComponentListenerImpl.InformType;
import de.linogistix.logviewer.processes.log.gui.component.TopComponentPanel;
import de.linogistix.logviewer.res.BundleResolver;
import java.io.Serializable;
import java.util.logging.Logger;
import javax.swing.JPanel;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
//import org.openide.util.Utilities;

/**
 * Top component which displays something.
 */
final class LogTopComponent extends TopComponent {
    private TopComponentPanel topComponentPanel = new TopComponentPanel(this);
    private TopComponentListenerImpl listener = new TopComponentListenerImpl();        
    private static LogTopComponent instance;
    /** path to the icon used by the component and its open action */
//    static final String ICON_PATH = "SET/PATH/TO/ICON/HERE";

    private static final String PREFERRED_ID = "LogTopComponent";

    private LogTopComponent() {
        initComponents();
        postCreationCode();
        setName(NbBundle.getMessage(BundleResolver.class, "CTL_LogTopComponent"));
        setToolTipText(NbBundle.getMessage(BundleResolver.class, "HINT_LogTopComponent"));
//        setIcon(Utilities.loadImage(ICON_PATH, true));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    /**
     * Gets default instance. Do not use directly: reserved for *.settings files only,
     * i.e. deserialization routines; otherwise you could get a non-deserialized instance.
     * To obtain the singleton instance, use {@link findInstance}.
     */
    public static synchronized LogTopComponent getDefault() {
        if (instance == null) {
            instance = new LogTopComponent();
        }
        return instance;
    }

    /**
     * Obtain the LogTopComponent instance. Never call {@link #getDefault} directly!
     */
    public static synchronized LogTopComponent findInstance() {
        TopComponent win = WindowManager.getDefault().findTopComponent(PREFERRED_ID);
        if (win == null) {
            Logger.getLogger(LogTopComponent.class.getName()).warning(
                    "Cannot find " + PREFERRED_ID + " component. It will not be located properly in the window system.");
            return getDefault();
        }
        if (win instanceof LogTopComponent) {
            return (LogTopComponent) win;
        }
        Logger.getLogger(LogTopComponent.class.getName()).warning(
                "There seem to be multiple components with the '" + PREFERRED_ID +
                "' ID. That is a potential source of errors and unexpected behavior.");
        return getDefault();
    }

    @Override
    public int getPersistenceType() {
        return TopComponent.PERSISTENCE_ALWAYS;
    }

 /*   @Override
    public void componentOpened() {
//        add(new JLabel("dsafds"))
    // TODO add custom code on component opening
//        LogTreeTableView view = new LogTreeTableView();
        System.out.println("open LogTopComponent");
        LogTreeTableView view = new LogTreeTableView();
        add (view, BorderLayout.CENTER);                
    }*/
    
    public void componentActivated() {
        listener.informComponents((JPanel)topComponentPanel,InformType.COMPONENT_ACTIVATED);
    }

    public void componentOpened() {
        listener.informComponents((JPanel)topComponentPanel,InformType.COMPONENT_OPENED);
    }
    
    public void componentClosed() {
        listener.informComponents((JPanel)topComponentPanel,InformType.COMPONENT_CLOSED);                
    }

    /** replaces this in object stream */
    @Override
    public Object writeReplace() {
        return new ResolvableHelper();
    }

    @Override
    protected String preferredID() {
        return PREFERRED_ID;
    }

    final static class ResolvableHelper implements Serializable {

        private static final long serialVersionUID = 1L;

        public Object readResolve() {
            return LogTopComponent.getDefault();
        }
    }
    
    private void postCreationCode() {
        add(topComponentPanel);        
    }
    
}
