/*
 * Copyright (c) 2006 - 2010 LinogistiX GmbH
 * 
 *  www.linogistix.com
 *  
 *  Project myWMS-LOS
 */
package de.linogistix.logviewer.processes.log.gui.component;

import java.awt.BorderLayout;
import javax.swing.ButtonGroup;
import org.openide.windows.TopComponent;

/**
 *
 * @author  artur
 */
public class TopComponentPanel extends javax.swing.JPanel {
    public CenterPanel centerPanel = new CenterPanel(this);
    public TopComponent topComponent;    
    
    /** Creates new form TopComponentPanel */
    public TopComponentPanel(TopComponent topComponent) {
        this.topComponent = topComponent;
        initComponents();
        add(centerPanel, BorderLayout.CENTER);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
